---
- name: add oob filter
  cisco.aci.aci_filter:
    validate_certs: no
    host: "{{ apic_url }}"
    username: "{{ aci_user }}"
    password: "{{ aci_password }}"
    filter: OOB-DEFAULT
    tenant: mgmt
    state: present

- name: add oob filter entry
  cisco.aci.aci_filter_entry:
    validate_certs: no
    host: "{{ apic_url }}"
    username: "{{ aci_user }}"
    password: "{{ aci_password }}"
    entry: PERMIT-ANY
    tenant: mgmt
    ether_type: ip
    filter: OOB-DEFAULT
    state: present

- name: add oob contract
  cisco.aci.aci_rest:
    validate_certs: no
    host: "{{ apic_url }}"
    username: "{{ aci_user }}"
    password: "{{ aci_password }}"
    path: /api/node/mo/uni/tn-mgmt.json
    method: post
    content:
      {
        "vzOOBBrCP" : {
          "attributes" : {
            "name" : "OOB-CONTRACT",
            "scope": "global"
          },
          "children" :
          [{
              "vzSubj" : {
                "attributes" : {
                  "name" : "OOB-DEFAULT"
                },
                "children" : [
                    {
                      "vzRsSubjFiltAtt" : {
                        "attributes" : {
                          "tnVzFilterName": "OOB-DEFAULT"
                        },
                      }
                    }
                ]
              }
            },
          ]
        }
      }

- name: bind provided oob contract
  cisco.aci.aci_rest:
    validate_certs: no
    host: "{{ apic_url }}"
    username: "{{ aci_user }}"
    password: "{{ aci_password }}"
    path: /api/node/mo/uni/tn-mgmt/mgmtp-default/oob-default.json
    method: post
    content:
      {
        "mgmtOoB" : {
          "attributes" : {
            "name" : "default"
          },
          "children" :
          [{
              "mgmtRsOoBProv" : {
                "attributes" : {
                  "tnVzOOBBrCPName" : "OOB-CONTRACT"
                }
              }
            },
          ]
        }
      }

- name: bind consumed oob contract
  cisco.aci.aci_rest:
    validate_certs: no
    host: "{{ apic_url }}"
    username: "{{ aci_user }}"
    password: "{{ aci_password }}"
    path: /api/node/mo/uni/tn-mgmt/extmgmt-default.json
    method: post
    content:
      {
        "mgmtInstP" : {
          "attributes" : {
            "name" : "OOB-DEFAULT"
          },
          "children" :
          [{
              "mgmtRsOoBCons" : {
                "attributes" : {
                  "tnVzOOBBrCPName" : "OOB-CONTRACT"
                }
              }
            },
            {
              "mgmtSubnet" : {
                "attributes" : {
                  "ip": "0.0.0.0/0"
                }
              }
            },
          ]
        }
      }

- name: add ipv4 address to out-of-band mgmt interface to nodes
  cisco.aci.aci_static_node_mgmt_address:
    validate_certs: no
    host: "{{ apic_url }}"
    username: "{{ aci_user }}"
    password: "{{ aci_password }}"
    epg: default
    pod_id: "{{ item.pod_id }}"
    type: out_of_band
    node_id: "{{ item.node_id }}"
    ipv4_address: "{{ item.address }}"
    ipv4_gw: "{{ item.gateway }}"
    state: present
  with_items:
    ## input examples
    #- { pod_id: 1, node_id: 101, address: 1.1.1.1/24, gateway: 1.1.1.254 } 
    #- { pod_id: 1, node_id: 102, address: 1.1.1.2/24, gateway: 1.1.1.254 } 
    #- { pod_id: 1, node_id: 1001, address: 1.1.1.3/24, gateway: 1.1.1.254 }
    #- { pod_id: 1, node_id: 1002, address: 1.1.1.4/24, gateway: 1.1.1.254 } 
