---
- name: add mcp interface policy
  cisco.aci.aci_interface_policy_mcp:
    validate_certs: no
    host: "{{ apic_url }}"
    username: "{{ aci_user }}"
    password: "{{ aci_password }}"
    mcp: "{{ item.name }}"
    admin_state: "{{ item.state }}"
    state: present
  with_items:
    - { name: MCP-ENABLED, state: yes }
    - { name: MCP-DISABLED, state: no }
