---
- name: add leaf switch profile
  cisco.aci.aci_switch_policy_leaf_profile:
    validate_certs: no
    host: "{{ apic_url }}"
    username: "{{ aci_user }}"
    password: "{{ aci_password }}"
    leaf_profile: "{{ item.profile }}"
    state: present
  with_items:
    ## input examples
    #- { profile: LF1001-SW-PROFILE }
    #- { profile: LF1002-SW-PROFILE }
    #- { profile: LF1001-1002-SW-PROFILE }
