---
- name: binding interface selector profiles to a switch policies leaf profiles
  cisco.aci.aci_interface_selector_to_switch_policy_leaf_profile:
    validate_certs: no
    host: "{{ apic_url }}"
    username: "{{ aci_user }}"
    password: "{{ aci_password }}"
    leaf_profile: "{{ item.profile }}"
    interface_selector: "{{ item.selector }}"
    state: present
  with_items:
    ## input examples
    #- { profile: LF1001-SW-PROFILE, selector: LF1001-INT-PROFILE } 
    #- { profile: LF1002-SW-PROFILE, selector: LF1002-INT-PROFILE } 
    #- { profile: LF1001-1002-SW-PROFILE, selector: VPC-LF1001-1002-INT-PROFILE } 

- name: adding switch policies leaf profiles selector associated node block range (w/ policy group)
  cisco.aci.aci_switch_leaf_selector:
    validate_certs: no
    host: "{{ apic_url }}"
    username: "{{ aci_user }}"
    password: "{{ aci_password }}"
    leaf_profile: "{{ item.profile }}"
    leaf: "{{ item.profile }}"
    from: "{{ item.start }}"
    to: "{{ item.end }}"
    policy_group: LF-PG
    leaf_node_blk: "{{ item.block }}"
    state: present
  with_items:
    ## input examples
    #- { profile: LF1001-SW-PROFILE, block: 1001, start: 1001, end: 1001 } 
    #- { profile: LF1002-SW-PROFILE, block: 1002, start: 1002, end: 1002 } 
    #- { profile: LF1001-1002-SW-PROFILE, block: 1001-1002, start: 1001, end: 1002 }
