---
- name: add spine switch profile
  cisco.aci.aci_rest:
    validate_certs: no
    host: "{{ apic_url }}"
    username: "{{ aci_user }}"
    password: "{{ aci_password }}"
    path: /api/node/mo/uni/infra.json
    method: post
    content:
      {
        "infraSpineP" : {
          "attributes" : {
            "name" : "{{ item.name }}"
          },
          "children" :
          [{
              "infraSpineS" : {
                "attributes" : {
                  "name" : "SPINE{{ item.node_id }}",
                  "type": "range"
                },
                "children" : [
                    {
                      "infraNodeBlk" : {
                        "attributes" : {
                          "name": "{{ item.node_id }}",
                          "from_": "{{ item.node_id }}",
                          "to_": "{{ item.node_id }}"
                        },
                      }
                    },
                    {
                      "infraRsSpineAccNodePGrp" : {
                        "attributes" : {
                          "tDn": "uni/infra/funcprof/spaccnodepgrp-SP-PG",
                        },
                      }
                    }
                ]
              }
            },
          ]
        }
      }
  with_items:
    ## input examples
    #- { name: SP101-SW-PROFILE, node_id: 101 } 
    #- { name: SP102-SW-PROFILE, node_id: 102 } 
