---
- name: binding interface selector profiles to a switch policies spine profiles
  cisco.aci.aci_rest:
    validate_certs: no
    host: "{{ apic_url }}"
    username: "{{ aci_user }}"
    password: "{{ aci_password }}"
    path: /api/node/mo/uni/infra.json
    method: post
    content:
      {
        "infraSpineP" : {
          "attributes" : {
            "name" : "{{ item.switch }}"
          },
          "children" :
          [{
              "infraRsSpAccPortP" : {
                "attributes" : {
                  "tDn": "uni/infra/spaccportprof-{{ item.interface }}"
                }
              }
            },
          ]
        }
      }
  with_items:
    ## input examples
    #- { switch: SP101-SW-PROFILE, interface: SP101-INT-PROFILE } 
    #- { switch: SP102-SW-PROFILE, interface: SP102-INT-PROFILE } 
