---
- name: Cisco ACI Bring-Up
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  - name: Touch the same file, but add/remove some permissions
    ansible.builtin.file:
      path: /etc/foo.conf
      state: touch
