---
- name: Cisco ACI Bring-Up
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Creating an empty file now
      file:
        path: /home/ec2-user/file4.txt
        state: touch
